In [3]:
import torch

import torch.nn as nn

# Define the input tensor with shape (batch_size, channels, height, width)
input_tensor = torch.randn(1, 1, 5, 5)  # Example: 1 sample, 1 channel, 5x5 image

# Define the Conv2d layer
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0)

# Print the input tensor
print("Input Tensor:")
print(input_tensor)
print(input_tensor.shape)

# Apply the convolutional layer to the input tensor
output_tensor = conv_layer(input_tensor)

# Print the output tensor
print("Output Tensor:")
print(output_tensor)
print(output_tensor.shape)

# Print the weights and bias of the convolutional layer
print("Weights:")
print(conv_layer.weight)
print("Bias:")
print(conv_layer.bias)


# Print the weights and bias of the convolutional layer
print("Weights:")
print(conv_layer.weight.shape)
print("Bias:")
print(conv_layer.bias.shape)

Input Tensor:
tensor([[[[-2.3607,  0.0731,  1.5371, -0.3933,  0.1807],
          [-0.3929,  1.7628,  0.9582,  1.0431, -0.5777],
          [ 0.9776,  0.2346, -0.3280,  1.5717,  1.2380],
          [ 0.3090, -0.0575,  0.3374, -1.6253, -0.0431],
          [-2.1578,  1.5524,  0.9755,  0.0189,  0.4957]]]])
torch.Size([1, 1, 5, 5])
Output Tensor:
tensor([[[[ 0.0276,  0.0158, -0.2662],
          [ 0.2455,  0.7607,  1.2595],
          [-0.2521, -0.2068, -0.4040]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 3, 3])
Weights:
Parameter containing:
tensor([[[[ 0.1932,  0.2226,  0.0313],
          [-0.1075,  0.2855, -0.0659],
          [-0.1228, -0.2805, -0.2786]]]], requires_grad=True)
Bias:
Parameter containing:
tensor([0.0314], requires_grad=True)
Weights:
torch.Size([1, 1, 3, 3])
Bias:
torch.Size([1])
